exports = [
  "Spoiler",            // 0
  "Front Bumper",
  "Rear Bumper",
  "Side Skirts",
  "Exhaust",
  "Rollcage",
  "Grille",
  "Bonnet",
  "Fenders and Arches",
  "Fenders",
  "Roof",
  "Engine",
  "Brakes",
  "Transmission",
  "Horn",
  "Suspension",
  "Armor",              // 16
  "",
  "Turbo",
  "",
  "",
  "",
  "Headlights",         // 22
  "Wheel Disks",
  "",
  "Plate Holders",
  "Vanity Plates",
  "Interior Trim",
  "Ornaments",
  "Interior Dash",
  "Dials",
  "Door Speakers",
  "Leather Seats",
  "Steering Wheels",
  "Column Shifters",
  "Plaques",
  "ICE",
  "Speakers",
  "Hydraulics",
  "Engine Block",
  "Air Filters",
  "Strut Braces",
  "Arch Covers",
  "Aerials",
  "Exterior Trim",
  "Tank",
  "Windows",
  "",
  "Livery",             // 48
  "",
  "",
  "",
  "",
  "",
  "",
  "Window Tint"
];